### ISSUE TITLE
Bitwise operators support

### ISSUE THREAD

**Issue by david942j** [rubysolo/dentaku#105]
Hi,
This is an awesome gem! I was looking for 'safe_eval' and this gem works perfect :).

But, may I make a wish that to support the `|` and `&` operators?
```
calculator.evaluate('1 | 2') #=> 3
calculator.evaluate('3 & 2') #=> 2
```

In addition, the `^` operator stands for the power operator currently.
Shouldn't it be the bitwise xor operator to fit most programming languages?

Thanks :)

### Update
I forked and try to add this feature, it seems works :)
https://github.com/rubysolo/dentaku/compare/master...david942j:master

**Comment by rubysolo** [comment]
Oh, sorry!  I missed your update!  Here's an implementation of `&` and `|`.

The reason that `^` is the power operator is that the original intent of the gem was to be able to execute Excel formulas in Ruby without much translation, and that's the Excel power operator.  (Of course, based on that goal, I suppose that the bitwise operations should have been `BITAND` and `BITOR`...)

**Comment by david942j** [comment]
Thanks a lot!
