### ISSUE TITLE
Unhelpful error message for `&&` and `||`

### ISSUE THREAD

**Issue by eabruzzese** [rubysolo/dentaku#113]
Hey there! I was experimenting with a few things in the `master` branch and came across this little issue.

The AST parser _really_ doesn't like the use of `&&` or `||`, and it throws a pretty unhelpful error message:

```
[8] pry(main)> Dentaku('1 && 1')
NoMethodError: undefined method `value' for nil:NilClass
from /Users/eabruzzese/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/dentaku-5534b88700fc/lib/dentaku/ast/bitwise.rb:13:in `value'
```

I imagine that this is a pretty common mistake, so it might be nice to have a more helpful error message if this happens.

**Comment by rubysolo** [comment]
`&&` and `||` are now essentially aliases for `AND` and `OR`.
