### ISSUE TITLE
UnboundVariableError only tells me about first variable

### ISSUE THREAD

**Issue by doutatsu** [rubysolo/dentaku#115]
While trying to evaluate for example `Dentaku('a + c')`, I will only get this exception `Dentaku::UnboundVariableError Exception: no value provided for variables: a`, while I am expecting to see `c` also get mentioned.

Checking `dependences`, `Dentaku` does return `["a", "c"]`. Unless I've missed it, I thought by design I should receive all the variables that are missing (Checking the source code)

**Comment by doutatsu** [comment]
Anything on this at all? Seems like I'll have to make a workaround

**Comment by rubysolo** [comment]
Yeah, I see why it's happening.  We only raise on attempted evaluation of an identifier without a value.  So as soon as we hit `a`, we immediately raise the error.  We could perhaps change the implementation to check for missing dependencies first.

**Comment by rubysolo** [comment]
We now check for dependencies before attempting evaluation.  If there are unbound variables, we raise with the full list.  Hope this helps!
