### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by deashay** [rubysolo/dentaku#117]
Hi, I really like your Gem, but my project needs the functionalities that are currently on master. Could you perhaps release a new version? I know I can specify master in Gemfile, but I'm developing an internal Gem that relies on yours, so I need a solid version dependency. I can work around it, but new release would make my life a lot easier : ) I've created an issue because there were no updates for 2 months and last release was in December ;x

**Comment by rubysolo** [comment]
Thanks for the nudge, released https://github.com/rubysolo/dentaku/tree/v2.0.11 .

**Comment by kolvi** [comment]
Dentaku version 2.0.11 gives my project a weird StackLevelTooDeep error. If I specify:
  gem 'dentaku', '2.0.10'
...in my Gemfile, everything works like a charm, but if I'm using the latest version (just specifying gem 'dentaku'), the program crashes at the very instant it's trying to parse something with Dentaku. Error log is the following:
13:35:32 worker.1   |  /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:137:in `_flat_hash'
13:35:32 worker.1   |  : stack level too deep (SystemStackError)
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `block in _flat_hash'
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `each'
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `inject'
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `_flat_hash'
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `block in _flat_hash'
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `each'
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `inject'
13:35:32 worker.1   |  	from /Users/xxxxxxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dentaku-2.0.11/lib/dentaku/calculator.rb:138:in `_flat_hash'
13:35:32 worker.1   |  	 ... 9020 levels...
Thanks for the great gem, by the way. I decided to post this as a comment to "New release" -post, I hope this is a right place (problem seems to be related to this version).

**Comment by rubysolo** [comment]
Sorry about that!  Can you post an example of a formula that is causing the error?
