### ISSUE TITLE
Tokenizer fails when single-quoted string contains apostrophe, even if escaped via backslash

### ISSUE THREAD

**Issue by mattdiamond** [rubysolo/dentaku#125]
If I pass in a string with apostrophes escaped:

    calculator.evaluate("process_location('martha\'s vineyard')")

the result is:

    RuntimeError: parse error at: '')'

I think I understand why this is happening: the tokenizer treats `martha\` as a single-quoted string, causing it to fail when it encounters the actual end-quote. However, I'm unsure how to handle this issue. What's the best way to escape an apostrophe in this situation? I assumed it could be escaped with a backslash, but apparently not.

**Comment by rubysolo** [comment]
Yes, Dentaku should support escaping, but currently does not.

As a workaround, can you use double quotes in your formulas?  You could escape them in the Ruby string, like:
```ruby
> Dentaku("LEN(\"ab'c\")")
=> 4
```

or use alternate quoting like:
```ruby
> Dentaku(%q{LEN("ab'c")})
=> 4```

**Comment by mattdiamond** [comment]
Thanks for the reply... I've switched to double quotes to solve the issue.
