### ISSUE TITLE
Datetime parser attempts to parse non-date parts of functions, dies with out of range error

### ISSUE THREAD

**Issue by tmikoss** [rubysolo/dentaku#128]
I'm using `dentaku` to provide power users a way to enter formulas. And for some reason some of said users prefer not to use spaces in their formulas. 

After version 2.0.9 a formula like a `2*40-40-40` no longer works, as the `40-40-40` part gets picked up by datetime parser that dies with `argument out of range` when trying to grasp the concept of 40th day of 40th month :).

Seeing that extracting valid dates via regex might be painful, maybe `available_scanners` of the token scanner could be made configurable? I know for a fact that dates are never used in formulas in my use case. Maybe trimming down the amount of parsers could even improve tokenization performance?

**Comment by rubysolo** [comment]
This is already possible!  😄 

```ruby
> Dentaku('2*40-40-40')
ArgumentError: argument out of range
> Dentaku::TokenScanner.scanners = Dentaku::TokenScanner.available_scanners - [:datetime]
> Dentaku('2*40-40-40')
=> 0
```
