### ISSUE TITLE
Dentaku.evaluate! not working

### ISSUE THREAD

**Issue by doutatsu** [rubysolo/dentaku#130]
I was wondering if there is a particular reason for not having self `evaluate!` method? I'd like to get exceptions without building the object in some cases.

**Comment by rubysolo** [comment]
No, there’s no particular reason, so we should add it.  You can send a PR if you would like, otherwise I’ll make the change when I have a chance.

**Comment by doutatsu** [comment]
Great, I'll make a PR if I find some time.

**Comment by doutatsu** [comment]
Awesome, sorry didn't get around to doing it myself 👍
