### ISSUE TITLE
Calculator function CONTAINS doesn't work!

### ISSUE THREAD

**Issue by Callion** [rubysolo/dentaku#136]
`calculator.evaluate("'A' CONTAINS 'A'")`
-> Dentaku::ParseError: Invalid statement
`calculator.evaluate("CONTAINS('AAA', 'A')")`
-> Dentaku::ParseError: Undefined function contains

```
variables = {'A' => 'aaa', 'B' => 'a'}
formula = "A CONTAINS B"
calculator.evaluate(formula, variables)
```
-> Dentaku::ParseError: Invalid statement

```
variables = {'A' => 'aaa', 'B' => 'a'}
formula = "CONTAINS(A, B)"
calculator.evaluate(formula, variables)
```
-> Dentaku::ParseError: Undefined function contains

In **calculator_spec.rb** isn't fucntion **CONTAINS** tested. What is correct way to use **CONTAINS** function? In READme is specified, that mentioned function is implemented.

EDIT: I'm trying to pass array of strings and check if given string is included in that array.

**Comment by Callion** [comment]
@rubysolo Can you take a look?

**Comment by rubysolo** [comment]
Hmm, can you tell me what version of the gem you are using?  This works for me on HEAD:

```
Dentaku('contains("a", "apple")')
# => true
```

**Comment by Callion** [comment]
Hmm, dont know what I did wrong, but its working now. I maybe add some tests, so other users won't end up like me. Thanks!
