### ISSUE TITLE
Handling multiple results

### ISSUE THREAD

**Issue by jonhue** [rubysolo/dentaku#137]
```
$ calculator = Dentaku::Calculator.new

$ calculator.evaluate('sqrt(4)')
=> 2.0
```

Please correct me if I am wrong, but shouldn't this return `[2.0, -2.0]`?

**Comment by david942j** [comment]
But in ruby(and common programming languages), `sqrt(4)` returns 2.0

**Comment by jonhue** [comment]
@david942j Well, still I believe that it would be appropriate for a calculator to return a correct result :)

**Comment by rubysolo** [comment]
No, the square root *function* [only returns positive numbers](https://www.reddit.com/r/askscience/comments/5l8x7q/if_the_square_root_function_only_returns_positive/).
