### ISSUE TITLE
Support for hashes and arrays in `#solve`

### ISSUE THREAD

**Issue by ndbroadbent** [rubysolo/dentaku#138]
I love that Dentaku already supports hashes and arrays when you store data in the calculator:

```ruby
calc = Dentaku::Calculator.new
calc.store(
  a: '25',
  b: {
    c: '55',
    d: ['2', '4', '6']
  }
)
calc.evaluate('b.d[2] * b.c')
# => 330
```

What would be even more amazing is if `calc.solve!` could also handle a hash with nested data structures, like this:

```ruby
calc = Dentaku::Calculator.new
need_to_compute = {
  a:  "25",
  b: {
    c: "a / 5",
    d: [2, 4, 6]
  },
  e: ["b.c + b.d[1]"],
  f: "e[0] + 1"
}
calc.solve!(need_to_compute)
```

I think I might be able to work around this by flattening my data before computations, but this would be really awesome.

**Comment by rubysolo** [comment]
Just pushed cf3f770 which enables the nested hashes part of this -- will work on the array support when I have a chance.

**Comment by rubysolo** [comment]
Ok!  Give fb12788 a shot.  😄

**Comment by ndbroadbent** [comment]
That's awesome, thanks very much! Exactly what I needed.

**Comment by ndbroadbent** [comment]
Hi @rubysolo, I just thought you might be interested to know how I'm using Dentaku in my app. I'm building a service that generates PDFs, and I've used Dentaku to add support for formulas for things like invoices and tax forms: https://formapi.io/news/2017-10-22/formulas

This library is super cool, so thanks for all your work!

**Comment by rubysolo** [comment]
Awesome, I'm glad it's useful.  Best of luck with your app -- looks like a neat/useful service!
