### ISSUE TITLE
Not differentiating between capital & lower case letters

### ISSUE THREAD

**Issue by jonhue** [rubysolo/dentaku#146]
```ruby
$ c = Dentaku::Calculator.new
$ c.store 'I': 2
$ c.store 'U': 4
$ c.store 'u': -4
$ c.evaluate 'I * U'
=> -8
```

Storing a value for `u` replaces the already stored value for `U`.

**Comment by rubysolo** [comment]
Case-insensitivity is a feature, not a bug.  😉 

The original use-case was supporting non-technical folks entering formulas into a website for later evaluation, and they were not always careful about case consistency in their variable names.  I think a case-sensitive option would be a good idea though.

**Comment by jonhue** [comment]
@rubysolo I'm not sure what your preference is. Do you have an extra argument to `Dentaku::Calculator.store` in mind or do you think about storing a permanent preference somewhere?

Adding case-sensitivity should be fairly straight forward:
https://github.com/rubysolo/dentaku/blob/dac1a0e9f1e656de3a9ac36a0a707d77198dbf7f/lib/dentaku/calculator.rb#L104
https://github.com/rubysolo/dentaku/blob/dac1a0e9f1e656de3a9ac36a0a707d77198dbf7f/lib/dentaku/calculator.rb#L107

Is there something I've missed?

**Comment by rubysolo** [comment]
I think the best options would be to either have the ability to make a calculator instance case-insensitive  or make a subclass of Calculator that is always case-insensitive.
