### ISSUE TITLE
Extending Tokenizer

### ISSUE THREAD

**Issue by doutatsu** [rubysolo/dentaku#150]
My app uses free text input and I've been building my own string analysis, to identify things like variables, numbers etc, which I then fed into Dentaku. But after months of improving it, I just realised how complex it and my not well tested Regex matching just didn't cut. So I was very excited to find you make a much better job at it with your `Tokenizer` class which I've started to use in my code. So I was wondering about two things:

1) What do you think about making a separate gem out of it, I think it has a lot of value on its own and would make it easier to contribute specifically to string analysis. 
2) ☝️  Specifically I was wondering about adding the ability to add new `TokenMatchers` as I deal with currencies. Currently something like `a = 1$` will fail and I have to rescue and then deal with it. But having an ability to just deal with tokens generated by `tokenize` would be much nicer.

**Comment by rubysolo** [comment]
I'm willing to make the Tokenizer a standalone gem if you feel it's valuable.  I'll close this issue once that's in place.

You might also look at registering a custom TokenScanner to handle your currency format in the meantime.

**Comment by doutatsu** [comment]
Thanks, I think it's really good on its own and splitting it will give it a better visibility. I'll look into `TokenScanner`, that sounds good!

**Comment by doutatsu** [comment]
Trying to understand how to incorporate custom `TokenScanner` based on your tests. Here an example I've been trying to make work:
```
currency_scan = Dentaku::TokenScanner.new(:currency, 'USD')
Dentaku::TokenScanner.register_scanner(:currency, currency_scan)
tokenizer = Dentaku::Tokenizer.new
tokenizer.tokenize('2 + USD')
```
Last line still returns `USD` as a `:identifier` rather than custom `:currency`

**Comment by rubysolo** [comment]
Yeah, manipulating the scan order is doable, but a little clunky.  ☹️ The scanners are stored in a hash, and we rely on the hash insert order as the order that the scanners are tried.  Since your custom scanner was added after all the standard scanners, it is last in the scan order, so in this case `:identifier` has already matched and consumed 'USD'.

Here's what you have to do to make it work today:

```ruby
# get a reference to the identifier scanner
identifier = Dentaku::TokenScanner.scanners.last
# remove it from the scanners hash
Dentaku::TokenScanner.scanners = Dentaku::TokenScanner.available_scanners - [:identifier]
# create and register your custom scanner as before
currency_scan = Dentaku::TokenScanner.new(:currency, 'USD') 
Dentaku::TokenScanner.register_scanner(:currency, currency_scan)
 # add identifier back, so it is now lower in priority
Dentaku::TokenScanner.register_scanner(:identifier, identifier)

tokenizer = Dentaku::Tokenizer.new
tokenizer.tokenize('x * 5 USD').map(&:category)
# => [:identifier, :operator, :numeric, :currency]
```

It would be nice to have something like an `insert_before` method on `TokenScanner`, or maybe add an option to `register_scanner` that would make this easier.

**Comment by doutatsu** [comment]
Thanks, I probably could have figured it out myself if I read the code better. I am happy to improve that when you split out it into its own gem, but its great I can make it work now 👍

**Comment by doutatsu** [comment]
So as I understand `TokenScanner` always uses a regexp. What do you think of being able to pass through a function instead? For example with currencies, I am using a separate gem that is much more effective at figuring out currencies. So instead of a simple regex, it could just depend on true/false from provided method call to decide on a token?

**Comment by rubysolo** [comment]
Yes, that seems reasonable.

**Comment by rubysolo** [comment]
I've done the initial extraction, repo is here: https://github.com/rubysolo/jrr_tokenizer.  It's very close to the internals of Dentaku, but I made a couple of name changes that had been bugging me for a while.
