### ISSUE TITLE
Performance issue when lot of equations and data

### ISSUE THREAD

**Issue by mestachs** [rubysolo/dentaku#152]
I've implemented a kind of excel file interpretation thanks to dentaku. 

Sample problem I try to solve : https://gist.github.com/mestachs/dbf38398ce07b9dc329ee86a019f6777

The performance are not that good when I reach 2822 formulas (+/- 40 sec). I've managed to improve a bit the performance by directly storing the decimal and integer values as data in the calculator and now I have 1383 expressions left and but it takes still 10 seconds to solve it.

```ruby
        equations = {}
        problem.map do |k, v|
            if v.to_i.to_s == v || v.to_f.to_s == v
              calc.store(k => v.to_f)
            else
              equations[k] = v
            end
        end
       solution = calc.solve!(equations)
```

from a profiling of my code I see that I always come back to "Calculator#store and _flat_hash" methods.
I don't know if it matters but I have some custom functions like(safe_div, ...)
I will try to isolate my tests to reproduce this.

any recommendation on the usage of dentaku or obvious reason on the performance degradation when having a big number of formulas ?

**Comment by rubysolo** [comment]
That's a neat use-case!

When I have some spare time, I'll try running your example locally and profiling -- maybe we can add some shortcuts to skip some of the processing.

**Comment by mestachs** [comment]
thanks I've managed to isolate my test

* clone/checkout the performance : https://github.com/mestachs/dentaku/blob/performance-issue/spec/perf_spec.rb#L12
* bundle exec rspec spec/perf_spec.rb
* stackprof tmp/stackprof-cpu-*.dump --text --limit 10 *

```
stackprof tmp/stackprof-cpu-*.dump --text --limit 10
==================================
  Mode: cpu(1000)
  Samples: 5695 (0.00% miss rate)
  GC: 1042 (18.30%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      6324 (111.0%)        1897  (33.3%)     Dentaku::FlatHash.from_hash
       498   (8.7%)         498   (8.7%)     Dentaku::StringCasing#standardize_case
      4710  (82.7%)         439   (7.7%)     Dentaku::Calculator#evaluate!
      1413  (24.8%)         392   (6.9%)     Dentaku::FlatHash.flatten_keys
      9209 (161.7%)         359   (6.3%)     Dentaku::BulkExpressionSolver#load_results
      4903  (86.1%)         333   (5.8%)     Dentaku::Calculator#store
       315   (5.5%)         315   (5.5%)     Dentaku::FlatHash.flatten_key
       145   (2.5%)         145   (2.5%)     Dentaku::Tokenizer#alias_regex
       123   (2.2%)         123   (2.2%)     Dentaku::BulkExpressionSolver#expression_with_exception_handler
        68   (1.2%)          41   (0.7%)     Dentaku::TokenScanner#scan
```

**Comment by rubysolo** [comment]
The first thing that jumps out is `FlatHash`.  If you're not using [nested data](https://github.com/rubysolo/dentaku/blob/master/spec/calculator_spec.rb#L69), we're wasting a lot of resources and we should add a way to disable that feature.

**Comment by mestachs** [comment]
I've tried to allow to opt-out of nested data in my fork.

Indeed disabling case insensitivity and nested data improves performance :
- with everything enabled : Finished in 22.01 seconds
- with case_sensitive: true : Finished in 19.27 seconds
- with case_sensitive: true, nested_data: false : Finished in 5.19 seconds

```
==================================
  Mode: cpu(1000)
  Samples: 1272 (0.70% miss rate)
  GC: 153 (12.03%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      1059  (83.3%)         234  (18.4%)     Dentaku::Calculator#evaluate!
      2143 (168.5%)         231  (18.2%)     Dentaku::BulkExpressionSolver#load_results
      1087  (85.5%)         195  (15.3%)     Dentaku::Calculator#store
       194  (15.3%)         194  (15.3%)     Dentaku::StringCasing#standardize_case
        83   (6.5%)          83   (6.5%)     Dentaku::Tokenizer#alias_regex
        69   (5.4%)          69   (5.4%)     Dentaku::BulkExpressionSolver#expression_with_exception_handler
        50   (3.9%)          31   (2.4%)     Dentaku::TokenScanner#scan
        10   (0.8%)          10   (0.8%)     Dentaku::Tokenizer#last_token
        93   (7.3%)           9   (0.7%)     Dentaku::Tokenizer#scan
         8   (0.6%)           8   (0.6%)     Dentaku::Token#length
```
