### ISSUE TITLE
Dentaku::ParseError: Unprocessed token close when using CASE statement

### ISSUE THREAD

**Issue by eterry1388** [rubysolo/dentaku#162]
When I try to do just a CASE statement, it works fine.  As soon as I prepend the case statement with additional formula strings, it bombs with the exception: `Dentaku::ParseError: Unprocessed token close`.

Here is a way to reproduce this bug:

```
formula = <<-FORMULA
2 + CASE 2
    WHEN 1
      THEN 5
    WHEN 2
      THEN 6
    ELSE
      0
    END
FORMULA

calculator = Dentaku::Calculator.new
calculator.evaluate(formula)

# => Dentaku::ParseError: Unprocessed token close
```

In the above example, as soon as you take off `2 + `, it works as expected.  Surrounding the case statement in parentheses does not solve the problem.

**Comment by rubysolo** [comment]
Good find, thank you for reporting this!
