### ISSUE TITLE
when nil in formula can evaluate as zero?

### ISSUE THREAD

**Issue by JYeeRen** [rubysolo/dentaku#164]
`c = Dentaku::Culcator.new`
`c.store(a: nil)`
`c.evaluate('a + 1')`
now output nil, should it be 1

**Comment by rubysolo** [comment]
I feel that coercing nil to zero would be even more inconsistent with Ruby and Excel -- this would be an error in either case.

```ruby
> a = nil
> a + 1
NoMethodError: undefined method `+' for nil:NilClass
```

Would it be possible to default nil to zero when you store the values?

```ruby
> c = Dentaku::Calculator.new
> c.store(a: nil || 0)
> c.evaluate('a + 1')
=> 1
```

**Comment by project-eutopia** [comment]
I agree with @rubysolo.

**Comment by JYeeRen** [comment]
@rubysolo You are right. I has solve the zero problem by add a function.
```
> c = Dentaku::Calculator.new
> c.add_function(:_, :numeric, ->(num) { num || 0 })
> c.store(a: nil)
> c.evaluate('_(a) + 1')
=> 1
```
