### ISSUE TITLE
evaluate does not capture all errors

### ISSUE THREAD

**Issue by tjbarker** [rubysolo/dentaku#165]
Not sure if this is desired functionality and I'm reading the README wrong.

current functionality:
1. (N.B evaluate is bang method)
`Dentaku::Calculator.new.evaluate!('1 + + 1') #=> Dentaku::ParseError: Dentaku::AST::Addition has too few operands`
2. (N.B evaulate is *not* bang method)
`Dentaku::Calculator.new.evaluate('1 + + 1') #=> Dentaku::ParseError: Dentaku::AST::Addition has too few operands`

expected functionality:
1. (N.B evaluate is bang method)
`Dentaku::Calculator.new.evaluate!('1 + + 1') #=> Dentaku::ParseError: Dentaku::AST::Addition has too few operands`
2. (N.B evaulate is *not* bang method)
`Dentaku::Calculator.new.evaluate('1 + + 1') #=> nil`

By my reading of `#evaluate!` and `#evaluate` in the README the non-bang `evaluate` should not raise an error.

I'm happy to contribute a solution but checking in to see if I should be updating the readme or adding extra errors to rescue from (or if I'm just dumb then I'm happy to just sit back down)

**Comment by rubysolo** [comment]
Good catch, thank you!  😎

**Comment by tjbarker** [comment]
hey, sorry, me again

found another instance of missed error catching.
In the `SUM` function the args are checked to ensure `!args.empty?`.
If `args => [nil]` no error is raised, then in the reduce, the casting to a number fails for the `nil`.

My assumption that `evaluate` should handle the error comes from being able to pass nil into a simple addition (not a sum) and it fails quietly.

`Dentaku::Calculator.evaluate('a + 1', a: nil) => nil`
`Dentaku::Calculator.new.evaluate('SUM(a, 1)', a: nil) => nil`

I've gone through and grabbed the rest of the methods (from [README#built in operations and functions](https://github.com/rubysolo/dentaku/tree/v3.1.0#built-in-operators-and-functions)) and tried them with nil arguments, (i.e. `Dentaku::Calculator.new.evaluate(eq, a: nil, b: nil)`)

The other thing that surprised me was that the AND and OR functions return true if nils are passed in.
 
```
equation       | error raised        | returned value | 
---------------|---------------------|----------------|
`AND(a,b)`     |                     | true           |
`IF(a, 1, 0)`  |                     | 0              |
`MAX(a,b)`     | TypeError: NilClass |                |
`MIN(a,b)`     | TypeError: NilClass |                |
`NOT(a,1,0)`   | Dentaku::ParseError |                |
`OR(a,b)`      |                     | true           |
`ROUND(a)`     | TypeError: NilClass |                |
`ROUNDDOWN(a)` | TypeError: NilClass |                |
`ROUNDUP(a)`   | TypeError: NilClass |                |
`SUM(a,b)`     | TypeError: NilClass |                |
```

**Comment by rubysolo** [comment]
Please never apologize for improving the world!

**Comment by tjbarker** [comment]
it looks as though `solve` isn't catching TSort::Cyclic
e.g `Dentaku::Calculator.new.solve(a: 'b', b: 'a') => raise TSort::Cyclic`

From the [README](https://github.com/rubysolo/dentaku#calculatorsolve--calculatorsolve)
```
calc = Dentaku::Calculator.new
calc.store(monthly_income: 50)
need_to_compute = {
  income_taxes:  "annual_income / 5",
  annual_income: "monthly_income * 12"
}
calc.solve!(need_to_compute)
#=> {annual_income: 600, income_taxes: 120}

calc.solve!(
  make_money: "have_money",
  have_money: "make_money"
}
#=> raises TSort::Cyclic
```
but when the none bang method is run
```
calc.solve(
  make_money: "have_money",
  have_money: "make_money"
}
expected #=> {make_money: :undefined, have_money: :undeinfed }
actual #=> raises TSORT::Cyclic
```

thanks again

**Comment by rubysolo** [comment]
Fixed in 39457bcfddac309813968dd1af3eec0230d34088, thanks!

**Comment by tjbarker** [comment]
Me again.

It looks like either `evaluate` doesn't rescue from `NoMethodError` and `ArgumentError` or the comparator class doesn't fail using `Dentaku::Error` and `Dentaku::ArgumentError`.

In the following examples I would have expected the returned value to be `nil`, rather than failing.

```
Dentaku::Calculator.new.evaluate('a < 1', a: 'b')        #=> nil
Dentaku::Calculator.new.evaluate('a < 1', a: 'b')        #=> ArgumentError: comparison of String with 1 failed
Dentaku::Calculator.new.evaluate('1 < a', a: nil)        #=> ArgumentError: comparison of Integer with nil failed
Dentaku::Calculator.new.evaluate('a < 1', a: nil)        #=> NoMethodError: undefined method `<' for nil:NilClass
Dentaku::Calculator.new.evaluate('a < 1', a: :undefined) #=> ArgumentError: comparison of Symbol with 1 failed
```

Again, I'm happy to help out and submit a PR but just wanted to know which direction to go in first

**Comment by rubysolo** [comment]
Yes, these should be caught, and I agree that ensuring that the comparator operations raise the `Dentaku` wrapped errors is probably a good first step.  If you'd like to submit a PR, that would be great; let me know if you get stuck or have questions.  Thanks!

**Comment by brigneld** [comment]
Hi @rubysolo, when do you expect these fixes will be incorporated into a release, please? We're very keen to get our hands on it, rather than creating a patch!

**Comment by rubysolo** [comment]
Pushed v3.2.1 to rubygems!

**Comment by brigneld** [comment]
Thanks for your quick response.
