### ISSUE TITLE
Display formula with replaced variable values

### ISSUE THREAD

**Issue by stanley90** [rubysolo/dentaku#168]
First, thanks for this cool gem.

I want to ask if it's possible to display a formula with variables replaced with their values, something like
`calculator.display('a + b = c', a: 1, b: 2, c: 3) => '1 + 2 = 3'`
Thanks

**Comment by rubysolo** [comment]
I'm glad it's useful!  😎 

It's not merged yet, but I have an implementation of the visitor pattern in a branch here: https://github.com/rubysolo/dentaku/commit/ba151066e9bfdea4e92352282d6281014eca37d4. The current version just prints out variable names, but it should be straightforward to replace them with the values from the context.

**Comment by stanley90** [comment]
Nice. When do you expect it to be done? Is some help needed?

**Comment by rubysolo** [comment]
If you're interested in helping with it, that would be great!  I would like to separate out the visitor algorithm from the per-node processing so that an end user could do something like `include Dentaku::Visitor::Infix` and then implement `process(node)`.  I pushed up a WIP commit that has an example.

**Comment by dklotz** [comment]
@rubysolo I would also be interested in the visitor implementation (in the end I want to limit the possible operators, functions etc, so only some operators, no `if`, no functions etc. and I think having this visitor implementation would be nicer then having to walk the AST myself), maybe you could create a WIP PR for your branch so the discussion on how to get this "production-ready" can be continued there?

**Comment by rubysolo** [comment]
Sure thing!  I opened #169 with some ideas so far.  Looking at the code again this morning, I think it might be better to have a single `visit` method rather than specific methods for each node type.  I'll close this issue and we can discuss further on the PR.
