### ISSUE TITLE
Support for Array / Array Literal

### ISSUE THREAD

**Issue by niyoko** [rubysolo/dentaku#170]
Is it possible to add array literal?  
Suggested syntax is `Dentaku('{1,2,3,4}')` resulting `[1,2,3,4]`. My current workaround is to create custom function

```
Dentaku::AST::Function.register(:array, :array, ->(*args) { args.flatten })
```
and use `ARRAY(1,2,3,4)`.

**Comment by coconup** [comment]
@rubysolo first of all thank you for the awesome work. 

Jumping in on this one, do you think it would be possible to have array literals evaluated with square brackets too? i.e. `calculator.evaluate('[1,2,3]')`
