### ISSUE TITLE
Date Time evaluation.

### ISSUE THREAD

**Issue by BKDruby** [rubysolo/dentaku#174]
Dentaku::Calculator.new.evaluate("2017-12-12 + 1")

Is Calculator support expressions like this? Mb with some options?

**Comment by rubysolo** [comment]
Perhaps we could relax the implementation of `Dentaku::AST::Addition` to ensure that the operands respond to the `:+` method rather than restricting to numeric only.  Would the 1 represent a number of days?

**Comment by BKDruby** [comment]
Yeah, I think it will be most popular use case.
As a feature I think whould be great if we have posibility to clarify it.
"2017-12-12 + 1 month"/ "2017-12-12 + 1 year"

and for datetime format
"2017-12-12 13:20 + 1 minute" "2017-12-12 13:20 + 1 hour" (hour IMHO should be as default)
