### ISSUE TITLE
Mistyped case statement raises RuntimeError

### ISSUE THREAD

**Issue by felgaete** [rubysolo/dentaku#182]
Having a formula using a mistyped case statement causes a RuntimeError when i think it should be a lib error (maybe Dentaku::TokenizeError)

Cases

```ruby
# case without end
Dentaku.resolve("CASE a when 'one' then 1")
# RuntimeError (Case missing switch variable)
```

```ruby
# case with mistyped when
Dentaku.resolve("CASE a whend 'one' then 1 end")
# RuntimeError (Expected first argument to be a CaseWhen)
```
```ruby
# case without then result
Dentaku.resolve("CASE a when 'one' then end")
# RuntimeError (Expected first argument to be a CaseWhen)
```
There is another [RuntimeError](https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/ast/case/case_conditional.rb#L14) that i can't get and should be considered too

Thanks!

**Comment by rubysolo** [comment]
Thanks for reporting this!
