### ISSUE TITLE
Warnings raised by Ruby

### ISSUE THREAD

**Issue by david942j** [rubysolo/dentaku#183]
Thanks for this great work!

I found there're three warnings shown if run Ruby with warning turns on:
`ruby -w -rdentaku -e Dentaku::Calculator.new`
```
/usr/lib/ruby/gems/2.5.0/gems/dentaku-3.3.0/lib/dentaku/flat_hash.rb:26: warning: shadowing outer local variable - h
/usr/lib/ruby/gems/2.5.0/gems/dentaku-3.3.0/lib/dentaku/parser.rb:114: warning: shadowing outer local variable - token
//usr/lib/ruby/gems/2.5.0/gems/dentaku-3.3.0/lib/dentaku/token_matcher.rb:19: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
```
It would be great that a library contains no such warnings.

**Comment by david942j** [comment]
Got one more warning:
`/usr/lib/ruby/gems/2.5.0/gems/dentaku-3.3.0/lib/dentaku/ast/arithmetic.rb:43: warning: BigDecimal.new is deprecated; use Kernel.BigDecimal method instead.`

**Comment by rubysolo** [comment]
Thanks for reporting!  I pushed a couple of commits to clean up warnings and make things more consistent.  I was unable to reproduce the BigDecimal warning on HEAD -- feel free to re-open if I missed something.

**Comment by david942j** [comment]
Thanks for the fix!

Maybe the BigDecimal warnings are raised only if Ruby version >= 2.5 (I got the warning under 2.5.3), I will check it later.

**Comment by david942j** [comment]
Confirmed that the deprecated message is shown on Ruby with version >= 2.5.
You can fix it with `%s/BigDecimal\.new/BigDecimal/g`, Rubies with version >= 2.0 all support the suggested method.

**Comment by rubysolo** [comment]
Are you testing HEAD, or the latest released gem?  I think this is fixed in HEAD.

**Comment by david942j** [comment]
Sorry I tested on the released gem, yes in HEAD this is fixed! Thanks!
