### ISSUE TITLE
Polish Notation

### ISSUE THREAD

**Issue by mmaruri** [rubysolo/dentaku#186]
Is there a way to disable polish notation?  We are trying to parse user submitted formulas and this is not a common/expected way to build a formula which we think will lead to unintended consequences for our app.

**Comment by rubysolo** [comment]
Everything should be in infix notation, not Polish notation currently.  Is there a specific formula parsing that you find confusing?

**Comment by rubysolo** [comment]
I'm going to close this, but feel free to reopen if this is still an issue.
