### ISSUE TITLE
An empty string as a variable value raises an ArgumentError

### ISSUE THREAD

**Issue by sliiser** [rubysolo/dentaku#190]
Passing an empty string as a value for a variable that expects a numeric value raises an error. Passing any other invalid value does not raise an error and just returns nil instead.

Allow me to demonstrate:
```ruby
Dentaku('a * 1', a: '1') # => 1
Dentaku('a * 1', a: 'invalid') # => nil
Dentaku('a * 1', a: nil) # => nil
Dentaku('a * 1', a: '') # => ArgumentError: invalid value for BigDecimal(): ""
```

This is due to format validation allowing empty string as a valid numeric value.
https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/ast/arithmetic.rb#L80

The current regexp (`/\A-?\d*(\.\d+)?\z/`) allows an empty string due to wanting to allow both '1' and '.1'. Easiest fix would probably be to add an empty string check onto the same line.

If you would like a PR, let me know.

**Comment by rubysolo** [comment]
Thanks for catching this!  A PR would be much appreciated.
