### ISSUE TITLE
Using lazily-evaluated variables

### ISSUE THREAD

**Issue by fsateler** [rubysolo/dentaku#192]
Hi, 

Thanks for this awesome gem.

In our current use case, we need to provide variables for the user, that might be quite expensive to calculate. Thus, I'd like to avoid calculating them if the formula does not reference them. Basically a version of:

```ruby
dentaku.evaluate!('1+2', expensive_value: proc{ calc_expensive_value })
```

Is this possible somehow, by passing some Node-derived class as the value?

**Comment by fsateler** [comment]
This is possible by using a Node-derived class:

```ruby
class LazyValue < Dentaku::AST::Node
  def initialize callable
    @callable = callable
  end
  def value(*)
    @callable.call
  end
end


dentaku.evaluate!('1+2', expensive_value: LazyValue.new(->{ calc_expensive_value})
```

It would be nice to have some support for this from the library itself though. Would a PR accepting procs in the data hash accepted?

**Comment by rubysolo** [comment]
Sorry for the late reply, I was on vacation when you opened the issue.

Yes, I think this looks useful.  Are you envisioning passing in raw procs, or something more like what you have with a wrapper class?  I think raw procs would be a little cleaner, but I wonder how much of a performance hit it would be to check if each variable needed to be evaluated.

**Comment by fsateler** [comment]
I was thinking that the LazyValue class (or whatever it ends up called) would be instantiated on memory load time.Something like:

```ruby
        key_or_hash.each do |key, val|
          memory[standardize_case(key.to_s)] = val.respond_to?(:call) ? LazyValue.new(val) : val
        end
```

Does this make sense?

**Comment by rubysolo** [comment]
Does 0dc672d give you what you need?

**Comment by fsateler** [comment]
Yes indeed! Thanks!
