### ISSUE TITLE
Unable to marshalize AST because of an anonymous class given as a node

### ISSUE THREAD

**Issue by dawlib** [rubysolo/dentaku#198]
Hello!

For instance, when I precompile an expression that has `MAX` function inside (not defined in `Dentaku::Parser::AST_OPERATIONS`) it generates AST with a node that is an anonymous class (ref: https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/ast/function_registry.rb#L12):
```
ast = Dentaku.calculator.ast('MAX(1, 2)')
#<#<Class:0x00007feb7fb45e20>:0x00007feb8c91a670 @args=[#<Dentaku::AST::Numeric:0x00007feb8c91a738 @value=1, @type=:numeric>, #<Dentaku::AST::Numeric:0x00007feb8c91a710 @value=2, @type=:numeric>]>
```
so when I want to marshalize it I receive error shown below:
```
Marshal.dump(ast)
*** TypeError Exception: can't dump anonymous class #<Class:0x00007feb7fb45e20>

nil
```

How can I solve this issue in order to be able to precompile to ASTs and then marshalize such expressions?

ref: https://github.com/rubysolo/dentaku/issues/185

**Comment by rubysolo** [comment]
Thanks for the PR!  I used your idea, but I munged the function name so that we don't have to ignore specially named functions.  There's still a chance of name collisions, but hopefully that's not too common.

**Comment by dawlib** [comment]
Thanks for taking care of it. Although, I would appreciate feedback in the PR so that I could learn more about the internals and apply a better solution myself.
