### ISSUE TITLE
Ambiguous syntax FUNCTION(arg,)

### ISSUE THREAD

**Issue by sliiser** [rubysolo/dentaku#205]
Currently according to my understanding, validity of syntax of formulas can be validated by calling `Dentaku::Calculator#ast` on them.

If ast returns without errors, the syntax is valid.

However, `CONCAT('1',)` is valid syntax according to AST
```
#<Dentaku::AST::StringFunctions::Concat:0x00007fc271b1c778 @args=[nil, #<Dentaku::AST::String:0x00007fc271b1cb60 @type=:string, @value="1">]>
```
but calling it will produce a `NoMethodError`.
```ruby
Dentaku.evaluate("CONCAT('1',)")
# => NoMethodError: undefined method `dependencies' for nil:NilClass
```
Reproducible with any function.

I'm happy to fixit myself if need be, but would need some guidance from the maintainer. Should I

1. consider this syntax invalid and refuse to produce the AST
2. consider it valid, treat it as `CONCAT('1')`
3. consider it valid, treat it as `CONCAT('1', NULL)`

**Comment by rubysolo** [comment]
Good find!  I think this should be considered invalid syntax.  If you would like to submit a PR, that would be great!

**Comment by sliiser** [comment]
Added PR. Also fixes arrays with similar issues `{1, 2, }`
