### ISSUE TITLE
Calculate Duration Between Two Dates 

### ISSUE THREAD

**Issue by thao33** [rubysolo/dentaku#207]
Hi dentaku,

I have a case that calculate duration between two dates.
Ex: `2020-04-06  -  2020-04-05 `

I expect the result is 1 (day). If it can not return 'day', just hours, minutes or seconds, whatever.. just type is numeric. But all I got is error like this.

```
Dentaku::ParseError: Dentaku::AST::Subtraction requires numeric operands, but got datetime
from /usr/local/bundle/gems/dentaku-3.3.4/lib/dentaku/parser.rb:338:in `fail!'
Caused by Dentaku::NodeError: Dentaku::AST::Subtraction requires numeric operands
from /usr/local/bundle/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:18:in `initialize'
``` 

Any chance my case will work by another way? such as `to_date` or sth like that?

**Comment by thao33** [comment]
Updated

After try add_function, my case can be resolved by the way like this:

```
c = Dentaku::Calculator.new

c.add_function(:duration, :numeric, ->(seconds) { minutes, seconds = seconds.divmod(60) ; hours, minutes = minutes.divmod(60); days, hours = hours.divmod(24) ; days })

c.add_function(:to_seconds, :numeric, ->(dateString) { dateString.to_date.to_time.to_i })

c.evaluate("duration(to_seconds('2020-04-06') - to_seconds('2020-04-05'))")

```
and finally the return result is 1 (day)

but if only the logical formula could be simpler .. no more to add function and long long formula..

**Comment by rubysolo** [comment]
This should work now!

**Comment by thao33** [comment]
@rubysolo 
wow ! 🤩Thank you for your support ! 🚀
Hope you'll release it soon ! 🙇‍♀️
