### ISSUE TITLE
Unexpected result of Date calculation

### ISSUE THREAD

**Issue by dyoshikawa** [rubysolo/dentaku#213]
Thanks for the great gem.

# Bug Report

Date calculation assume UTC timezone.
So miscalculation if UTC was not set on a machine.

## Prepare

Date calculation is a new feature.
So use `specific_install`.

```
gem install specific_install
gem specific_install -l https://github.com/rubysolo/dentaku
```

### Code

```ruby
require 'date'
require 'dentaku'

calc = Dentaku::Calculator.new

res1 = calc.evaluate('2020-04-30 - 2020-04-01')
puts res1

res2 = calc.evaluate('value - 2020-04-01', { value: Date.new(2020, 4, 30) })
puts res2
``` 

### Execute

```
$ TZ=UTC ruby test.rb
29/1 # res1
29/1 # res2
```

Those are expected values.

```
$ TZ=Asia/Tokyo ruby test.rb

29/1 # res1
235/8 # res2
```

Expected `res2` value is `29/1` in this case, too.

**Comment by rubysolo** [comment]
It looks like what is happening is that the internal times are local, but the time you are storing in the context `Date.new(2020, 4, 30)` is in UTC.  Can you try ensuring that the value you pass in is in your local TZ?  Something like:

```{ value: Time.local(2020, 4, 30).to_datetime }```

**Comment by dyoshikawa** [comment]
Really thanks!
Your suggestion is working well.
