### ISSUE TITLE
using comparison operators with nil arguments make non-bang solve method raise an error

### ISSUE THREAD

**Issue by aossowski** [rubysolo/dentaku#252]
Here's an example:

```
> calc = Dentaku::Calculator.new; calc.store(a: nil); calc.solve("a > 1")
Dentaku::Error: undefined method `>' for nil:NilClass
```

same formula does not raise an error when using `evaluate`

```
> Dentaku.evaluate("a > 1", a: nil)
=> nil
```

Looks like it's because `BulkExpressionSolver`  rescues `Dentaku::ArgumentError` but not `Dentaku::Error`  https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/bulk_expression_solver.rb#L92-L97 while `evaluate` rescues both https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/calculator.rb#L48-L50

I'm happy to submit a PR with a fix - just wanted to hear your thoughts first.

**Comment by rubysolo** [comment]
Thank you!
