### ISSUE TITLE
Fails to parse addition of two percentages

### ISSUE THREAD

**Issue by shaicoleman** [rubysolo/dentaku#258]
```
require 'dentaku'
calc = Dentaku::Calculator.new
calc.evaluate('10%')
=> 0.1
calc.evaluate('10%+10%')
=> nil
```

The following exception is raised and swallowed:
`Dentaku::ParseError (Dentaku::AST::Addition has too few operands)`

**Comment by rubysolo** [comment]
Thanks for the report -- fixed in 5601209!
