### ISSUE TITLE
Dentaku::AST::Subtraction requires numeric operands, but got integer

### ISSUE THREAD

**Issue by Nghi93** [rubysolo/dentaku#263]
```ruby
calculator = Dentaku::Calculator.new

calculator.add_function(:custom, :integer, lambda do
  1
end)

calculator.solve(
  a: "1",
  b: "CUSTOM() - a"
)
```

procudes the error mentioned in the title.

**Comment by Nghi93** [comment]
Quickfix is
```
calculator.add_function(:custom, :numeric, lambda do
  1
end)
```

**Comment by rubysolo** [comment]
Fixed in 475a9e7, thanks!

**Comment by Nghi93** [comment]
Thank you for fixing this bug so fast.
Could you create a patch release, please?

**Comment by Nghi93** [comment]
just a quick question:
There are other descendants of numerics:

Numeric.descendants
=> [ActiveSupport::Duration::Scalar, Date::Infinity, BigDecimal, Integer, Float, Rational, Complex]

Do you neeed to support them as well?

```
calculator = Dentaku::Calculator.new

calculator.add_function(:custom, :big_decimal, lambda do
  BigDecimal.new("1.23")
end)

calculator.solve(
  a: "1",
  c: "CUSTOM() - a",
)
```
