### ISSUE TITLE
Float question

### ISSUE THREAD

**Issue by zy-design** [rubysolo/dentaku#269]
hi, rubysolo
   c = Dentaku::Calculator.new
   c.evaluate('a+b+c', a: 0, b: 0, c: 77.9) =>0.7790000000000001e2
but i wish i got result equal : c.evaluate('a+b+c', a: 0, b: 0, c: 77.9) =>77.9
how can i do?

**Comment by zhchsf** [comment]
You can use decimal, ex: c.evaluate('a+b+c', a: 0, b: 0, c: 77.9.to_d)

**Comment by zy-design** [comment]
thanks guys @a5-stable @rubysolo
