### ISSUE TITLE
set var_name causing solve to fail

### ISSUE THREAD

**Issue by Nghi93** [rubysolo/dentaku#279]
Debugging dentaku computations is really painful. It is hard to understand which line causes the error.
The BulkExpressionSolver has the information which line causes the error, but the information is not passed to the exception handler proc. 
I can see 2 options:
* pass the var_name which causes the error as a 2nd parameter to the error handling proc in BulkExpressionSolver
* add something like `var_name` to each Exception class, so you could ask the exception later on

We can help with implementation. Just need a direction to start with.

Best regards

**Comment by Nghi93** [comment]
I just saw that there is an recipient_variable field on some type of Errors.
Can we add this to Dentaku::ArgumentError as well?

**Comment by rubysolo** [comment]
Yes, I think adding the variable to the exception would be a good solution.  Thanks in advance!

**Comment by Nghi93** [comment]
I added a PR. Would be nice if you could create a new release after merging that one.

**Comment by rubysolo** [comment]
Closed in #280

**Comment by rubysolo** [comment]
Released [v3.5.1](https://rubygems.org/gems/dentaku/versions/3.5.1)
