### ISSUE TITLE
Isn't `add_functions` supposed to be class method?

### ISSUE THREAD

**Issue by sabbiu** [rubysolo/dentaku#299]
The code given here

https://github.com/rubysolo/dentaku/blob/main/lib/dentaku/calculator.rb#L38-L41

```rb
def add_functions(fns)
  fns.each { |(name, type, body, callback)| add_function(name, type, body, callback) }
  self
end
```

Similar to how `add_function` is a class method, I was thinking if `add_functions` should also be a class method.

How to initialize multiple functions at once?

**Comment by rubysolo** [comment]
Thanks for the report!
