### ISSUE TITLE
v3.5.2: Calculating difference between two stored dates returns :undefined

### ISSUE THREAD

**Issue by sjieg** [rubysolo/dentaku#312]
Hey, first of all, thanks for the amazing work on Dentaku, we've been using it our project successfully for a long time now and it adds a lot of value!

**Steps to reproduce**

```Ruby
calculator = Dentaku::Calculator.new
calculator.store("d1", Date.parse("2024/01/02"))
calculator.store("d2", Date.parse("2024/01/06"))
calculator.solve("d1 - d2")
```

**expected**

```
{"[]"=>(-4/1)}
```

**actual since 3.5.2**

```
{"[]"=>:undefined}
```

I didn't test the actual commit that broke this (or maybe this is new expected behaviour), but I suspect this commit: https://github.com/rubysolo/dentaku/commit/8aa37bc68c69ef1f66f5b75cb38be35e2fed1498
@ignatiusreza maybe you could have a look?

**Comment by rubysolo** [comment]
Thanks for reporting this!  It should work as expected in [v3.5.3](https://github.com/rubysolo/dentaku/releases/tag/v3.5.3).

**Comment by sjieg** [comment]
Good stuff, glad I could help and thanks for the good work!
