### ISSUE TITLE
Dentaku calculations slowing down with time

### ISSUE THREAD

**Issue by leikind** [rubysolo/dentaku#45]
Hi,

I noticed in my application that certain calculations got slower and slower with time. I profiled my code and found out that the offender was Dentaku. The version used in the application is 1.2.1. (1.2.4 behaves differently, more below).

Running Dentaku calculations i was able to find out that slowing down occurs when

* there is a custom function, even if it is not used
* the hash of variables submitted to `calculator.evaluate` as the second argument contains 2 copies of the same variable, downcased and lowercased. Example:  `{"R1"=>100000, "R2"=>0,  "r1"=>100000, "r2"=>0, ...}`. This is a way I made sure my variables were case-insensitive :-)

Both factors should be present to reproduce this behavior.

I fixed this problem in my app by removing lowercased characters, but still, this is such an interesting case, I thought you'd be interested. What is really amazing is that I am not talking  about one `Dentaku::Calculator` object here performing all calculations, no, `Dentaku::Calculator` is created for every calculation. Does Dentaku store some data globally?

Here is my test script:

```ruby
#!/usr/bin/env ruby

require 'dentaku'
require 'benchmark'

puts "Dentaku version #{Dentaku::VERSION}"
puts "Ruby version #{RUBY_VERSION}"

with_duplicate_variables = [
  "R1+R2+R3+R4+R5+R6",
  {"R1"=>100000, "R2"=>0, "R3"=>200000, "R4"=>0, "R5"=>500000, "R6"=>0, "r1"=>100000, "r2"=>0, "r3"=>200000, "r4"=>0, "r5"=>500000, "r6"=>0}
]

without_duplicate_variables = [
  "R1+R2+R3+R4+R5+R6",
  {"R1"=>100000, "R2"=>0, "R3"=>200000, "R4"=>0, "R5"=>500000, "R6"=>0}
]

def test(args, custom_function: true)
  calls = [ args ] * 100

  4.times do |i|

    bm = Benchmark.measure do

      calls.each do |formule, bound|

        calculator = Dentaku::Calculator.new

        if custom_function
          calculator.add_function(
            name:      :sum,
            type:      :numeric,
            signature: [:arguments],
            body:      ->(args){args.reduce(0){|a, b| a + b }}
          )
        end

        calculator.evaluate(formule, bound)
      end
    end

    puts "  run #{i}: #{bm.total}"
  end
end

case ARGV[0]
when '1'
  puts "with duplicate (downcased) variables, with a custom function:"
  test(with_duplicate_variables, custom_function: true)

when '2'
  puts "with duplicate (downcased) variables, without a custom function:"
  test(with_duplicate_variables, custom_function: false)

when '3'
  puts "without duplicate (downcased) variables, with a custom function:"
  test(without_duplicate_variables, custom_function: true)

when '4'
  puts "with duplicate (downcased) variables, without a custom function:"
  test(without_duplicate_variables, custom_function: false)
end

```

Output for version 1.2.1 is

```
$ ./test_dentaku.rb 1 && ./test_dentaku.rb 2 && ./test_dentaku.rb 3 && ./test_dentaku.rb 4
Dentaku version 1.2.1
Ruby version 2.2.1
with duplicate (downcased) variables, with a custom function:
  run 0: 0.88
  run 1: 2.43
  run 2: 3.9499999999999997
  run 3: 5.54
Dentaku version 1.2.1
Ruby version 2.2.1
with duplicate (downcased) variables, without a custom function:
  run 0: 0.13999999999999999
  run 1: 0.14
  run 2: 0.14
  run 3: 0.13999999999999996
Dentaku version 1.2.1
Ruby version 2.2.1
without duplicate (downcased) variables, with a custom function:
  run 0: 0.010000000000000002
  run 1: 0.009999999999999995
  run 2: 0.010000000000000009
  run 3: 0.01999999999999999
Dentaku version 1.2.1
Ruby version 2.2.1
with duplicate (downcased) variables, without a custom function:
  run 0: 0.010000000000000002
  run 1: 0.009999999999999995
  run 2: 0.010000000000000009
  run 3: 0.009999999999999995
```
As you see, only the first case shows some significant slowing down.

But version 1.2.4 works differently:

```
$ ./test_dentaku.rb 1 && ./test_dentaku.rb 2 && ./test_dentaku.rb 3 && ./test_dentaku.rb 4
Dentaku version 1.2.4
Ruby version 2.2.1
with duplicate (downcased) variables, with a custom function:
  run 0: 0.23
  run 1: 0.5599999999999999
  run 2: 0.87
  run 3: 1.2100000000000002
Dentaku version 1.2.4
Ruby version 2.2.1
with duplicate (downcased) variables, without a custom function:
  run 0: 0.060000000000000005
  run 1: 0.06
  run 2: 0.07
  run 3: 0.05999999999999997
Dentaku version 1.2.4
Ruby version 2.2.1
without duplicate (downcased) variables, with a custom function:
  run 0: 0.23
  run 1: 0.57
  run 2: 0.89
  run 3: 1.2000000000000002
Dentaku version 1.2.4
Ruby version 2.2.1
with duplicate (downcased) variables, without a custom function:
  run 0: 0.060000000000000005
  run 1: 0.06
  run 2: 0.06
  run 3: 0.06999999999999998
```

As you see

* There is still some slowing down in certain cases
* but it not that terrible as with 1.2.1
* the hash of variables with lowercased and downcased copies of a variable has no effect
* calculations slow down when there is a custom function, i.e. case 1 and 3.

I am very curious, could you please help me understand this behavior?

For now I am staying on 1.2.1, because I do need custom functions, and even modest slowing down is not good for my application.

Thank you

**Comment by rubysolo** [comment]
I checked this out, and it's a problem in the `Rules` class.  I don't like the current class-based approach and I'm working on a better implementation.  I'm not sure how long it will take, but I'll close this issue when it is fixed.

**Comment by leikind** [comment]
Thank you. 

Can you just shed the light on why exactly it is slowing down? Some internal global structures growing, GC problems...?

**Comment by rubysolo** [comment]
It looks like a memory leak.  I did an allocation trace, and the number of objects (especially Hashes and Arrays) allocated by the Rules class grows over time.

**Comment by rubysolo** [comment]
Thank you for the benchmarking script!  I added allocation tracing and put it in the repo.

**Comment by leikind** [comment]
I'm glad I could help
