### ISSUE TITLE
Divide by Zero in `solve!`

### ISSUE THREAD

**Issue by glanotte** [rubysolo/dentaku#46]
If any of the equations that you pass to `solve!` divides by zero, the whole method errors out. I see why that could be a preferred approach. We would like to be able to return `nil` instead of a full error so the rest of the equations can complete. 

I was curious if you felt this might be a more desirable default as well or if you would prefer the current behavior. And if you would prefer the current behavior, perhaps passing in an optional error handler or something along those lines?

I am happy to submit a PR, but I thought it would be best to get an idea of direction from you all first.

Thanks! Geoff

**Comment by rubysolo** [comment]
Thanks for reporting this!  I think I would prefer that `solve!` raises an exception, but it would be nice to have a plain `solve` method that would return nil in this case.  Alternatively, I think it would make sense to have the ability to pass in an error handler to `solve!`.

**Comment by glanotte** [comment]
That seems like a good path forward, I will get started on a PR. thanks!

**Comment by glanotte** [comment]
Thanks for the fast turn around!
