### ISSUE TITLE
Latest version 2.0.1 Modulus (%) not supported

### ISSUE THREAD

**Issue by jacobhummer** [rubysolo/dentaku#53]
Utilizing the modulus function you get error:
KeyError: key not found: :mod
dentaku-2.0.1/lib/dentaku/parser.rb:127:in `fetch'
dentaku-2.0.1/lib/dentaku/parser.rb:127:in `operation'
dentaku-2.0.1/lib/dentaku/parser.rb:41:in `parse'
dentaku-2.0.1/lib/dentaku/calculator.rb:55:in `block in ast'
dentaku-2.0.1/lib/dentaku/calculator.rb:54:in `fetch'
dentaku-2.0.1/lib/dentaku/calculator.rb:54:in `ast'
dentaku-2.0.1/lib/dentaku/calculator.rb:36:in `block in evaluate!'
dentaku-2.0.1/lib/dentaku/calculator.rb:73:in `store'
dentaku-2.0.1/lib/dentaku/calculator.rb:34:in `evaluate!'
dentaku-2.0.1/lib/dentaku/calculator.rb:28:in `evaluate'

**Comment by rubysolo** [comment]
Good catch, thanks!
