### ISSUE TITLE
expression not parsed

### ISSUE THREAD

**Issue by atzorvas** [rubysolo/dentaku#54]
this one doesn't work
any idea?

    [49] pry(main)> calculator.evaluate("(((695759/735000)^(1/(1981-1991)))-1)*1000")
    ZeroDivisionError: divided by 0
    from /home/atzorvas/.rvm/gems/ruby-2.2.1@cessda/gems/dentaku-2.0.2/lib/dentaku/ast/arithmetic.rb:64:in `**'

**Comment by rubysolo** [comment]
Sorry about that -- thanks for reporting the issue!

**Comment by atzorvas** [comment]
:tada:
