### ISSUE TITLE
RuntimeError: parse error on evaluate

### ISSUE THREAD

**Issue by assisthiago** [rubysolo/dentaku#57]
Hi guys, I need some help.. I've just met this gem and it's perfect for the functionality that I'm working on, but I can't get it to work.

Here's a copy of what I've been trying, hope I can get some help: https://gist.github.com/assisthiago/e1d15421aa12a9a3687e

Cheers!

**Comment by rubysolo** [comment]
Do you need your variable names to be surrounded by brackets and exclamation points?  Dentaku expects variables to be "word" characters (letters, numbers and underscores) only.  I added a modified example to your gist that uses acceptable variable names.

**Comment by mcpenchel** [comment]
Actually I do, but I'll try some workarounds. Thank you!
