### ISSUE TITLE
Error when using function result with identifier arguments in further operation

### ISSUE THREAD

**Issue by cweyer** [rubysolo/dentaku#59]
I am having trouble using a function with identifiers as arguments and then using the result in a more complex equation:

```ruby
c = Dentaku::Calculator.new
c.store("multi_color" => true, "number_of_sheets" => 5000, "sheets_per_minute_black" => 2000, "sheets_per_minute_color" => 1000)
c.evaluate('number_of_sheets / if(multi_color, sheets_per_minute_color, sheets_per_minute_black)')
#=> NoMethodError: undefined method `type' for #<Dentaku::AST::Identifier:0x007fc051849f90>
```

Using integers or floats as arguments to the if function works without problems. Also not using the computed result of the if function any further works, too (i.e. only evaluating the denominator). Since it calls type on identifier I assume it tries to get the type of the argument of the if function before the identifiers were actually resolved into concrete numbers. Or am I doing something wrong?

**Comment by rubysolo** [comment]
Fixed, thanks for reporting!

**Comment by cweyer** [comment]
I'm the one how has to thank you for fixing that so fast :) Amazing!
