### ISSUE TITLE
Array parameter being flattened with others

### ISSUE THREAD

**Issue by jheth** [rubysolo/dentaku#65]
The following function works well when the expression evaluates to two strings, but fails when haystack is an Array and needle is a single value.

```
calculator.add_function(
    :is_included,
    :logical,
    ->(haystack, needle) {
        haystack.include?(needle)
    }
)
```

The flat_map method is causing the first array parameter to be flattened with the 2nd string parameter. Is there a way this can be supported?

``` 
// lib/dentaku/ast/function.rb 
36  def value(context={})
37     args = @args.flat_map { |a| a.value(context) }
38     self.class.implementation.call(*args)
39  end
```

**Comment by rubysolo** [comment]
It seems that the `flat_map` there is unnecessary.  Thanks for reporting this!
