### ISSUE TITLE
Handling variable values of wrong data type in numeric operations

### ISSUE THREAD

**Issue by pharlez** [rubysolo/dentaku#72]
```
calculator.evaluate("10 + 'abc'")
=> throws RuntimeError

calculator.evaluate("10 + x", x: "abc")
=> 10
```

Is this reasonable? It seems to me that the latter should also follow the pattern where it returns `nil`, with its `evaluate!` counterpart throwing an Exception.

**Comment by rubysolo** [comment]
Agreed -- I'll look into a fix for this.

**Comment by rubysolo** [comment]
Fixed, thank you for reporting this!

**Comment by pharlez** [comment]
Great, thanks! :)
