### ISSUE TITLE
Money gem support

### ISSUE THREAD

**Issue by tito0224** [rubysolo/dentaku#73]
Hi great job on this gem. It's awesome!

I'd like to know if you have support planned for the money gem. I'd love to be able to use money objects as inputs to the formula.

I'd be more than happy to take a swing at implementing this. Is this something you'd consider including? Can you provide any pointers on how I should go about implementing this type of support?

Thanks!

**Comment by rubysolo** [comment]
Thank you -- I'm glad you like it!  :smile: 

I hadn't considered adding support for money objects.  I'm not opposed, but I think I'd like to know more about what you would like to see.  Would money values essentially be treated as normal numbers during the formula evaluation but returned back as money objects again?  What would something like the following do?

```ruby
Dentaku('5 + x', x: Money.new(5, "USD"))
```

**Comment by tito0224** [comment]
Sorry for the delayed response here. 

I would expect what your example not to work since you can't add or subtract non Money types from Money object - but you can multiply or divide them.

So in order to make that work, I would expect the user to have to do something like:

`Dentaku('y + x', y: Money.new(50, "USD"), x: Money.new(5, "USD"))`

but some thing like this should be fine:

`Dentaku('5 * x', x: Money.new(5, "USD"))`

I would expect it to return money objects if the inputs are money objects. I can see this causing problems is you try to mix types, however maybe throwing the exception or returning nil would be sufficient in this case, and put the burden on the developer to use the correct types.

Thanks again for your response and great gem!

**Comment by rubysolo** [comment]
If you want to take a shot at implementing this, that would be fine.  I would prefer not to add the money gem as a hard dependency -- just something that adds support if the gem is already available.  You might be able to get away with just changing how the numeric validation and casting works.  (See `cast` and `validate_numeric` in `lib/dentaku/ast/arithmetic.rb`)
