### ISSUE TITLE
When solving an expression with dependencies, are cyclic errors always raised before unbound variable errors?

### ISSUE THREAD

**Issue by rcanand** [rubysolo/dentaku#77]
Sorry for entering this as an issue - it is more of a clarification - I didn't find a contact link on the main page.

Is it guaranteed, that, given a hash of expressions without any stored values, solve! will always return cyclic errors before unbound variable errors? I checked and it seemed to work, but wanted to confirm, as that is critical to my scenario.

```
    calc = Dentaku::Calculator.new
    # case 1
    need_to_compute = {
      income_taxes: "annual_income / 5",
      annual_income: "monthly_income * 12"
    }

    # case 2
    calc.solve! need_to_compute #=> Unbound variable error
    
    need_to_compute = {
      income_taxes: "annual_income / 5",
      annual_income: "monthly_income * 12",
      monthly_income: 'annual_income'
    }
    
    calc.solve! need_to_compute #=> Cyclic error 
    # Is it always the case that cyclic error will be raised before 
    # unbound variable error in cases like case 2 above?
```

**Comment by rubysolo** [comment]
Yes, that's correct.  Dependency resolution (which can raise Cyclic error) happens [first](https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/bulk_expression_solver.rb#L44), then evaluation (which can raise Unbound Variable) happens [later](https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/bulk_expression_solver.rb#L55).
