### ISSUE TITLE
Formulas without any calculation return the original input (instead of casting to numeric type)

### ISSUE THREAD

**Issue by mockdeep** [rubysolo/dentaku#80]
We got a bit of surprising output when trying to round the result of a formula calculation:

```irb
> Dentaku::Calculator.new.evaluate!(some_formula, some_variables).round(3)
NoMethodError: undefined method `round' for "52.0":String
```

It turns out `Dentaku` returns the original variable if no calculation is done:

```irb
> Dentaku::Calculator.new.evaluate!('a', a: '52.0').round(3)
NoMethodError: undefined method `round' for "52.0":String
```

This seems like really surprising behavior. I would expect evaluating a formula with `Dentaku` to always return a numeric type.

**Comment by rubysolo** [comment]
The only problem is that Dentaku also handles string literals and functions.  For example:
```ruby
> Dentaku::Calculator.new.evaluate!('CONCAT(a, b)', a: "abc", b: "def")
=> "abcdef"
```

If you know that you will always be passing numeric values, can you explicitly cast inputs?

**Comment by mockdeep** [comment]
Hmm, interesting. Out of curiosity, why does it handle string operations?

Does it decide to cast based on they type of calculation being performed? We could handle it on our end, but it would be nice to have it just be handled transparently so we don't forget to cast anywhere. I suppose we could write our own wrapper class. Another thought is if maybe `Dentaku` could have some sort of default configuration around it. I don't anticipate us ever using it for string operations.

**Comment by rubysolo** [comment]
Well, it's by no means complete, but the original intent was to handle Excel formulas, including string manipulation.

That's correct, it casts input to numeric if it is being used in an arithmetic operation: https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/ast/arithmetic.rb#L20

I could see adding a config option that would cast all output to numeric, but a wrapper class seems like a good solution too.

**Comment by mockdeep** [comment]
Alright, we'll go the wrapper approach for now.

Trying to think if there's a graceful way to handle both use-cases, but nothing comes to mind. I don't suppose string operations are mutually exclusive from numerical operations? E.g., what if you looked for string operations, and if you don't find any, assume it's numerical?

**Comment by rubysolo** [comment]
I would prefer the configuration setting that casts all return values to numeric over a solution that automatically casts if no string operations are present, since the end-user could opt-in to the behavior.

**Comment by mockdeep** [comment]
:+1: makes sense.
