### ISSUE TITLE
How to resolve a formula with conditional dependencies?

### ISSUE THREAD

**Issue by tmikoss** [rubysolo/dentaku#81]
I'm stumped by a case where a conditional formula sometimes depends on another formula, that might not be resolvable all the time. A simplified case for example:
```
calc = Dentaku::Calculator.new

data = {
  what_i_want: "IF(a != 0, formula, 0)",  
  formula: "10/a",  
  a: 0  
} 
```

I'm looking for the value of `what_i_want`. However, when running `calc.solve!(data)`, I'm faced with `Dentaku::ZeroDivisionError`, because it also tries to solve `formula`.

`evaluate!` works in this case:
```
calc.evaluate!("IF(a != 0, formula, 0)", { formula: "10/a", a: 0 } )
=> 0
```

However, it doesn't handle dependency formulas:
```
calc.evaluate!("IF(a != 0, formula, 0)", { formula: "10/a", a: 1 } )
=> "10/a"
```

I could go on fetching in all the dependencies, resolving them and storing in memory. However, I would still end up trying to evaluate `10/0` at one point and getting errors:

```
calc.store(a: 0)
=> #<Dentaku::Calculator:0x007f9f763802f8 @ast_cache={}, @memory={"a"=>0}, @tokenizer=#<Dentaku::Tokenizer:0x007f9f76380208>>
calc.dependencies("IF(a != 0, formula, 0)")
=> ["formula"]
```

Is there any way to handle this situation? Besides just evaluating the result of `calc.evaluate!` again and again, until it stops changing?

**Comment by rubysolo** [comment]
I apologize for the delay in responding.  You can use the non-bang `solve` in this case.  I have added a [test](https://github.com/rubysolo/dentaku/commit/e7c5dd93da4436f2c994eacfc1cce23fffd7ac9f#diff-89af9f29ceaa3b34954574331b266a68R146) illustrating how it handles this situation.

**Comment by tmikoss** [comment]
Looks great, thank you!
