### ISSUE TITLE
disable cache for certain formula

### ISSUE THREAD

**Issue by wendy0402** [rubysolo/dentaku#82]
Hi, this is really an awesome library, I love it! especially your idea to cache the formula. However, is it possible to disable cache for certain formula? I've seen the code and it seems dentaku can't do that, but in case I'm wrong.
the use case for this such as, user want to validate their formula. Therefore no need to cache it, however when they are sure that the formula works of course we need to cache it.
If it's good idea I don't mind to create pull request about it

**Comment by rubysolo** [comment]
Thanks!  I'm glad you find it useful.

I think that's a good idea -- I was thinking about some sort of selective cache clearing, but it probably makes more sense to have a way to opt-out of the cache.  I would love a PR for this!

**Comment by wendy0402** [comment]
what I see from dentaku code, the process of caching the formula happens here https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/calculator.rb#L54
my initial idea is some sort of this:
```
def ast(expression, opt = {})
      @ast_cache.fetch(expression) {
        Parser.new(tokenizer.tokenize(expression)).parse.tap do |node|
          @ast_cache[expression] = node if Dentaku.cache_ast? && !opt[:disable_cache]
        end
      }
    end
```
and update others part that use it of course
what do you think? the drawback of course when they want to disable cache need to do somehow like this:
```ruby
calc = Dentaku::Calculator.new
calc.evaluate('1 + test', {test: 2}, disable_cache: true)
```

are you okay with that?

**Comment by rubysolo** [comment]
It's always a little messy to pass two hashes as arguments.  Maybe a block method would be better?  Something like:

```ruby
calc = Dentaku::Calculator.new
calc.disable_cache { |c| c.evaluate('1 + test', {test: 2}) }
```

What do you think?

**Comment by wendy0402** [comment]
I like the idea! Will start working on it

**Comment by muescha** [comment]
and add a `clear_cache`:

```ruby
calc = Dentaku::Calculator.new
calc.clear_cache #remove all
calc.clear_cache "expression" #remove one cached
calc.clear_cache { |expression| expression =~ /test/ }
```

**Comment by wendy0402** [comment]
sorry for take it too long.
My daily job and several side job cause me to abandon this issue.
@rubysolo please check it and what do you think about @muescha suggestion?

**Comment by rubysolo** [comment]
No worries -- I fully understand.  Thank you for taking the time to send this in!  I think @muescha 's suggestion would be good as well, but your PR is a great start.

**Comment by wendy0402** [comment]
nice! I'll help you to implement it

**Comment by rubysolo** [comment]
Also implemented `clear_cache` in 048af16

**Comment by rubysolo** [comment]
Oh, just saw your message!  I apologize if you wanted to work on this -- thank you for offering!

**Comment by wendy0402** [comment]
@rubysolo no worries, just want to help, nice to know it has been implemented
