### ISSUE TITLE
Get rid of generic exception raising

### ISSUE THREAD

**Issue by seppsepp** [rubysolo/dentaku#85]
Raising just a RuntimeError exception like in https://github.com/rubysolo/dentaku/blob/5f117cd745605367a8f72ddd0742b8941e06a61e/lib/dentaku/tokenizer.rb#L16 makes it hard to fetch and identify them as Dentaku related ones. Named exceptions should be thrown ... like it is done at several other places in the code.

Just my 2 cents ;) .

**Comment by rubysolo** [comment]
I agree!  Fixed in e95d0ac 😄

**Comment by seppsepp** [comment]
Nice, thanks!
