### ISSUE TITLE
Is there a factorial available?

### ISSUE THREAD

**Issue by annoying-dog** [rubysolo/dentaku#92]
Would be nice to have a factorial if it's not too hard to make. e.g. `10!` would return `3628800`

**Comment by rubysolo** [comment]
I don't think I want to add syntax to support this, but it's pretty easy to add it as a custom function if you don't mind calling it as `FACT(n)` in your formulas.

Something like:
```ruby
calc.add_function(:fact, :numeric, ->(n) { (1..n).inject(:*) })
```
