### ISSUE TITLE
ArgumentError: negative argument

### ISSUE THREAD

**Issue by jordynchuhaloff** [rubysolo/dentaku#93]
Hi, I'm getting `ArgumentError: negative argument` when I do:

`calculator.evaluate!('-(F2)', 'F2' => '5')`

Looks like it's only an issue when F2 is a string.. this does not cause the error:

`calculator.evaluate!('-(F2)', 'F2' => 5)`

Strings do appear to be supported though, since this doesn't throw an error either:

`calculator.evaluate!('F2', 'F2' => '5')`

Any thoughts on this? Thanks!

**Comment by scudelletti** [comment]
I have the same problem here.

I'm trying to debug and I noticed that the exception is raised [here](https://github.com/rubysolo/dentaku/blob/master/lib/dentaku/ast/negation.rb#L10).

**Comment by rubysolo** [comment]
Fixed in #c2ba0ff, thanks @scudelletti !
