### ISSUE TITLE
Combinator fails on incomplete statements

### ISSUE THREAD

**Issue by tobmatth** [rubysolo/dentaku#97]
Dentaku::Ast::Combinator#valid_node? seems to fail on incomplete logical statements:

    pry(main)> Dentaku('true AND')
    NoMethodError: undefined method `dependencies' for nil:NilClass
    from [..]/dentaku-2.0.10/lib/dentaku/ast/combinators.rb:20:in `valid_node?'

**Comment by rubysolo** [comment]
Thanks for pointing this out!
