### ISSUE TITLE
CONCAT with more than 2 arguments

### ISSUE THREAD

**Issue by breckenedge** [rubysolo/dentaku#99]
Thanks for this very useful library! It's pretty neat, I'm considering using it to safely evaluate some user-entered functions.

The `CONCAT` function can take any number of arguments, but will only concatenate the first two arguments:

```ruby
Dentaku::Calculator.new.evaluate('CONCAT(a, b, c)', a: 'a', b: 'b', c: 'c') #=> 'ab'
```

So to get full concatenation, I have to chain multiple concats:

```ruby
Dentaku::Calculator.new.evaluate('CONCAT(a, CONCAT(b, c))', a: 'a', b: 'b', c: 'c') #=> 'abc'
```

I was thinking of opening a PR that would allow any number of arguments to `CONCAT` and combine them all.

**Comment by rubysolo** [comment]
Great, I'm glad it's useful!

I think making `CONCAT` variadic is a great idea, and I would welcome a PR for that.  Thanks!
